title: Tiny tools
#logo:
description: tiny tools for personal use, work in progress

remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
